Contributors.md

Created my name and contributed according to the workshop held by gdsc uet lahore virtually

add mahrukh

---

Contributors.md

Add Lever Manx to the contributors list

Add Lever Manx to the contributors list

---

README.md

- Add instructions related to contribution file changings.
- Add git install guidelines.
- Add fork button and username changes

Update Readme contribution guidelines

---

Contributors.md

Please review my PR and merge it with `hacktoberfest-accepted` label

Add Hardik-desai to the Contributors list

---

C++/find_peak_element.cpp

This is a program written in c++ language ,and it will give you index of the peak element.

added program to find out peak element

---

Python/Spelling.py

Spelling Corrector with Python

---

Python/NumberGuesse.py

A Number Guessing Program with Py

---

Python/mergesort.py

Written MergeSort Algo With Python

MergeSort Code with Python

---

Python/Web_Scraper.py

Created Web Scraper With Python

Web_Scraper.py

---

Python/Dice.py

Hey! Can You Merge this with hackerfest-accepted...Thanks

Dice Roll Generator

---

Python/Reminder.py

Python Program for Reminder with Duration

A Reminder Program

---

Python/Convertor.py

Convert Your Currency with Python

Currency Convertor

---

Python/password.py

Random Password Generator

---

C++/StirlingApprox.cpp

Program for Stirling Interpolation Formula
Stirling Approximation or Stirling Interpolation Formula is an interpolation technique, which is used to obtain the value of a function at an intermediate point within the range of a discrete set of known data points . Stirling Formula is obtained by taking the average or mean of the Gauss Forward and Gauss Backward Formula . Both the Gauss Forward and Backward formula are formulas for obtaining the value of the function near the middle of the tabulated set .

Stirling Approximation

---

Python/Text_Detection/README.md
Python/Text_Detection/text_detection.py
README.md

please check the repo and Accept the PR
- In this project, I have used Python and its OpenCV to catch the images and for detection of the text, pytesseract was used.
- It works well you can use it anywhere just clone it in a system with python.

Text Detector 📜🔍

---

Contributors.md
Python/Huffman_Encoding.ipynb

Added Huffman Encoding algorithm for better learning.

Added Huffman Encoding Notebook

---

Python/kadane.py

Python implementation of Kadane Algorithm to find the maximum continuous sum subarray

Kadane Algorithm

---

dijkstra.c

Given a graph and a source vertex in the graph, find the shortest paths from the source to all vertices in the given graph.

Dijkstra’s Shortest Path Algorithm

---

Contributors.md
Python/calculator.py

add a program for calculator in python

Added calculator.py

---

C++/KMPAlgorithm.cpp
C++/KadaneAlgorithm.cpp
Contributors.md

Added KMP Algorithm to CPP Codes

KMP Algorithm - CPP

---

Contributors.md
Ruby/linkedList.rb

added ruby code for linked list

kami922 ruby LinkedL

---

README.md

- Update the hacktoberfest cover.

[doc]: change hacktoberfest cover
